language: python
env:
    - TOXENV=py36
    - TOXENV=py37
    - TOXENV=py38
    - TOXENV=py39
    - TOXENV=pypy
    - TOXENV=pypy3
    - TOXENV=pep8
install:
    - pip install tox
script:
    - tox -e $TOXENV
